<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Chapter_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get chapter by ID
     */
    function get_chapter($ID)
    {
        return $this->db->get_where('chapter',array('ID'=>$ID))->row_array();
    }
        
    /*
     * Get all chapter
     */
    function get_all_chapter()
    {
        $this->db->order_by('ID', 'desc');
        return $this->db->get('chapter')->result_array();
    }
        
    /*
     * function to add new chapter
     */
    function add_chapter($params)
    {
        $this->db->insert('chapter',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update chapter
     */
    function update_chapter($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('chapter',$params);
    }
    
    /*
     * function to delete chapter
     */
    function delete_chapter($ID)
    {
        return $this->db->delete('chapter',array('ID'=>$ID));
    }
}
