<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lession_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lession by ID
     */
    function get_lession($ID)
    {
        return $this->db->get_where('lession',array('ID'=>$ID))->row_array();
    }
        
    /*
     * Get all lession
     */
    function get_all_lession()
    {
        $this->db->order_by('ID', 'desc');
        return $this->db->get('lession')->result_array();
    }
        
    /*
     * function to add new lession
     */
    function add_lession($params)
    {
        $this->db->insert('lession',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lession
     */
    function update_lession($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('lession',$params);
    }
    
    /*
     * function to delete lession
     */
    function delete_lession($ID)
    {
        return $this->db->delete('lession',array('ID'=>$ID));
    }
}
