<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Course extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Course_model');
    } 

    /*
     * Listing of course
     */
    function index()
    {
        $data['course'] = $this->Course_model->get_all_course();
        
        $data['_view'] = 'course/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new course
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('Name','Name','max_length[255]');
		$this->form_validation->set_rules('Description','Description','max_length[255]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'isDelete' => $this->input->post('isDelete'),
				'ID_User' => $this->input->post('ID_User'),
				'Status' => $this->input->post('Status'),
				'Name' => $this->input->post('Name'),
				'Description' => $this->input->post('Description'),
				'DateStart' => $this->input->post('DateStart'),
				'Postion' => $this->input->post('Postion'),
            );
            
            $course_id = $this->Course_model->add_course($params);
            redirect('course/index');
        }
        else
        {
			$this->load->model('User_model');
			$data['all_users'] = $this->User_model->get_all_users();
            
            $data['_view'] = 'course/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a course
     */
    function edit($ID)
    {   
        // check if the course exists before trying to edit it
        $data['course'] = $this->Course_model->get_course($ID);
        
        if(isset($data['course']['ID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('Name','Name','max_length[255]');
			$this->form_validation->set_rules('Description','Description','max_length[255]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'isDelete' => $this->input->post('isDelete'),
					'ID_User' => $this->input->post('ID_User'),
					'Status' => $this->input->post('Status'),
					'Name' => $this->input->post('Name'),
					'Description' => $this->input->post('Description'),
					'DateStart' => $this->input->post('DateStart'),
					'Postion' => $this->input->post('Postion'),
                );

                $this->Course_model->update_course($ID,$params);            
                redirect('course/index');
            }
            else
            {
				$this->load->model('User_model');
				$data['all_users'] = $this->User_model->get_all_users();

                $data['_view'] = 'course/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The course you are trying to edit does not exist.');
    } 

    /*
     * Deleting course
     */
    function remove($ID)
    {
        $course = $this->Course_model->get_course($ID);

        // check if the course exists before trying to delete it
        if(isset($course['ID']))
        {
            $this->Course_model->delete_course($ID);
            redirect('course/index');
        }
        else
            show_error('The course you are trying to delete does not exist.');
    }
    
}
