<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lession extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Lession_model');
    } 

    /*
     * Listing of lession
     */
    function index()
    {
        $data['lession'] = $this->Lession_model->get_all_lession();
        
        $data['_view'] = 'lession/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new lession
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('Name','Name','max_length[255]');
		$this->form_validation->set_rules('Description','Description','max_length[255]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'isDelete' => $this->input->post('isDelete'),
				'ID_Chapter' => $this->input->post('ID_Chapter'),
				'Status' => $this->input->post('Status'),
				'Name' => $this->input->post('Name'),
				'Description' => $this->input->post('Description'),
				'Position' => $this->input->post('Position'),
				'Content' => $this->input->post('Content'),
            );
            
            $lession_id = $this->Lession_model->add_lession($params);
            redirect('lession/index');
        }
        else
        {
			$this->load->model('Chapter_model');
			$data['all_chapter'] = $this->Chapter_model->get_all_chapter();
            
            $data['_view'] = 'lession/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a lession
     */
    function edit($ID)
    {   
        // check if the lession exists before trying to edit it
        $data['lession'] = $this->Lession_model->get_lession($ID);
        
        if(isset($data['lession']['ID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('Name','Name','max_length[255]');
			$this->form_validation->set_rules('Description','Description','max_length[255]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'isDelete' => $this->input->post('isDelete'),
					'ID_Chapter' => $this->input->post('ID_Chapter'),
					'Status' => $this->input->post('Status'),
					'Name' => $this->input->post('Name'),
					'Description' => $this->input->post('Description'),
					'Position' => $this->input->post('Position'),
					'Content' => $this->input->post('Content'),
                );

                $this->Lession_model->update_lession($ID,$params);            
                redirect('lession/index');
            }
            else
            {
				$this->load->model('Chapter_model');
				$data['all_chapter'] = $this->Chapter_model->get_all_chapter();

                $data['_view'] = 'lession/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The lession you are trying to edit does not exist.');
    } 

    /*
     * Deleting lession
     */
    function remove($ID)
    {
        $lession = $this->Lession_model->get_lession($ID);

        // check if the lession exists before trying to delete it
        if(isset($lession['ID']))
        {
            $this->Lession_model->delete_lession($ID);
            redirect('lession/index');
        }
        else
            show_error('The lession you are trying to delete does not exist.');
    }
    
}
